name: Build my keyboards

on: [push]

jobs:
  KBD75-Tecur:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Environment
      run: |
          git clone --recurse-submodules https://github.com/qmk/qmk_firmware.git
          cd qmk_firmware
          util/qmk_install.sh
    - name: Make
      run: make kbdfans/kbd75/rev1:tecur
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
